### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yasirroni** [bughht/Thomas-Calculus-Review#1]
Hi @bughht, your review really help me a lot. Please add a License so that other know what is the limitation of using your writings here. If we are free to do anything with it, can you please confirm it at least on this issue. Thanks a lot.

**Comment by bughht** [comment]
I'm glad to see that my personal calculus notes help you. And thank you for your suggestion, WTFPL License has been added, so there's no limitation for using my writings. Enjoy :)
